import type { ColorName } from './colors';

/** Raw brand tokens from the Calio redesign. */
export const brand = {
  primary: '#69B32B',
  secondary: '#D77B52',
  primaryPressed: '#4F8D25',
  lightBackground: '#F6F8EF',
  lightSurface: '#FFFFFF',
  lightText: '#1B2518',
  lightMutedText: '#7A8674',
  lightBorder: '#DCE6D4',
  darkBackground: '#141A12',
  darkSurface: '#202A1D',
  darkText: '#F1F5E9',
  darkMutedText: '#AAB6A2',
  darkBorder: '#3A4935',
  lightDisabledBackground: '#E2E8DD',
  lightDisabledText: '#8A9585',
  darkDisabledBackground: '#35402F',
  darkDisabledText: '#7F8C78',
} as const;

export type ThemeColors = Record<ColorName, string>;

export const lightColors: ThemeColors = {
  primary: brand.primary,
  primaryPressed: brand.primaryPressed,
  primaryMuted: '#E8F4DC',
  primaryBright: '#7FC43A',
  secondary: brand.secondary,
  secondaryPressed: '#C06842',
  secondaryMuted: '#F8EAE3',
  secondaryHot: '#E8956A',
  background: brand.lightBackground,
  surface: brand.lightSurface,
  surfaceMuted: '#EEF2E6',
  textPrimary: brand.lightText,
  textSecondary: '#4A5544',
  textMuted: brand.lightMutedText,
  textDisabled: '#AAB6A2',
  textOnPrimary: brand.darkBackground,
  textOnSecondary: brand.lightText,
  border: brand.lightBorder,
  borderStrong: '#C5D2BB',
  buttonDisabledBackground: brand.lightDisabledBackground,
  buttonDisabledText: brand.lightDisabledText,
  success: brand.primaryPressed,
  successBright: brand.primary,
  warning: brand.secondary,
  error: '#C44B4B',
  errorMuted: '#FCECEE',
  info: '#4A7A8C',
  macroCalories: brand.primary,
  macroProtein: '#4A7A8C',
  macroCarbs: brand.secondary,
  macroFat: '#A75A79',
  macroActivity: brand.primaryPressed,
};

export const darkColors: ThemeColors = {
  primary: brand.primary,
  primaryPressed: brand.primaryPressed,
  primaryMuted: '#1F2E18',
  primaryBright: '#7FC43A',
  secondary: brand.secondary,
  secondaryPressed: '#C06842',
  secondaryMuted: '#3A2A22',
  secondaryHot: '#E8956A',
  background: brand.darkBackground,
  surface: brand.darkSurface,
  surfaceMuted: '#1A2218',
  textPrimary: brand.darkText,
  textSecondary: '#D5DDCC',
  textMuted: brand.darkMutedText,
  textDisabled: '#6B7664',
  textOnPrimary: brand.darkBackground,
  textOnSecondary: brand.lightText,
  border: brand.darkBorder,
  borderStrong: '#4A5A44',
  buttonDisabledBackground: brand.darkDisabledBackground,
  buttonDisabledText: brand.darkDisabledText,
  success: '#7FC43A',
  successBright: brand.primary,
  warning: brand.secondary,
  error: '#E07070',
  errorMuted: '#3A2222',
  info: '#7AA8B8',
  macroCalories: brand.primary,
  macroProtein: '#7AA8B8',
  macroCarbs: brand.secondary,
  macroFat: '#C47A98',
  macroActivity: '#7FC43A',
};
